config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'pages#home'
get 'about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		
	end

	def about
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<table>
	
	<tr>
		<td><img width='100px' <%= image_tag 'tanuki anime.png' %> </td>
		<td><h1>This is what we are all about</h1></td>
	</tr>

</table>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<HTML>
<HEAD>


</HEAD>

<BODY>

<TABLE align = "center">
	<TR>
		<TD align="center"> <h1> Welcome to my Webpage! </h1></TD>
	</TR>
	<TR>
		<TD><%= image_tag 'tanuki anime.png' %></TD>
	</TR>
</TABLE>


<TABLE align="center">
	<TR>
		<TD width=50%>hey, this is my paragraph of information.  I wouuld like this appear on the left side of the table<BR/>
		What do you think about that? <BR/>
		Anyway.. this is all well and good, but I need to get back to my coding now..
	   </TD>

    	<TD width=50%> 
    		here is more text. that should be read by the users.<br/>
    	So, yeah, here we are just chatting away and wondering if anyone will ever read this.  I hope that these words find you well and you and your family are doing great.  Thanks.</TD>



	</TR>



</TABLE>


</BODY>

</HTML>
<%= link_to 'About', about_path %>